/**
 * Precomputes how many tilings each date of the board admits.
 *
 * Counting one date takes on the order of a second, so the 2562 possible
 * month/day/weekday combinations are worked out once here and shipped as a
 * table rather than recomputed in the browser.
 *
 * Usage:
 *
 *   npx vite-node scripts/build-solution-counts.ts
 *
 * The whole run is roughly 45 minutes on one core. To use several, run one
 * process per shard and then merge the parts:
 *
 *   npx vite-node scripts/build-solution-counts.ts -- --shards 4 --shard 0 --out part-0.json
 *   …
 *   npx vite-node scripts/build-solution-counts.ts -- --merge part-0.json,part-1.json,…
 *
 * `src/core/solutionCounts.ts` reads the generated table; the tests spot-check
 * it against the live solver, so a stale table cannot go unnoticed.
 */

import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { countSolutions } from '../src/core/solver.ts';
import { daysInMonth, isMonth, type PuzzleDate } from '../src/core/date.ts';
import type { Weekday } from '../src/core/board.ts';

const WEEKDAYS = 7;
const DAYS = 31;
const MONTHS = 12;
export const TABLE_SIZE = MONTHS * DAYS * WEEKDAYS;

/** Position of one month/day/weekday combination in the flat table. */
export function tableIndex(month: number, day: number, weekday: number): number {
  return ((month - 1) * DAYS + (day - 1)) * WEEKDAYS + (weekday - 1);
}

/** Every combination worth counting: impossible dates such as 31 February are skipped. */
function combinations(): readonly PuzzleDate[] {
  const out: PuzzleDate[] = [];
  for (let month = 1; month <= MONTHS; month += 1) {
    if (!isMonth(month)) continue;
    // 2024 is a leap year, so 29 February is included.
    const last = daysInMonth(2024, month);
    for (let day = 1; day <= last; day += 1) {
      for (let weekday = 1; weekday <= WEEKDAYS; weekday += 1) {
        out.push({ month, day, weekday: weekday as Weekday });
      }
    }
  }
  return out;
}

interface Args {
  readonly shard: number;
  readonly shards: number;
  readonly out: string | null;
  readonly merge: readonly string[] | null;
}

function parseArgs(argv: readonly string[]): Args {
  const get = (name: string): string | null => {
    const at = argv.indexOf(`--${name}`);
    if (at === -1) return null;
    return argv[at + 1] ?? null;
  };
  const merge = get('merge');
  return {
    shard: Number(get('shard') ?? 0),
    shards: Number(get('shards') ?? 1),
    out: get('out'),
    merge: merge === null ? null : merge.split(',').filter((name) => name !== ''),
  };
}

function writeTable(counts: readonly number[], destination: string): void {
  const rows: string[] = [];
  for (let month = 1; month <= MONTHS; month += 1) {
    const from = tableIndex(month, 1, 1);
    const slice = counts.slice(from, from + DAYS * WEEKDAYS);
    rows.push(`  // month ${month}\n  ${slice.join(', ')},`);
  }

  const source = `/**
 * Generated by scripts/build-solution-counts.ts — do not edit by hand.
 *
 * Number of distinct tilings for every month/day/weekday combination, flattened
 * as \`((month - 1) * ${DAYS} + (day - 1)) * ${WEEKDAYS} + (weekday - 1)\`.
 * Impossible dates such as 31 February hold 0.
 */

export const SOLUTION_COUNTS: readonly number[] = [
${rows.join('\n')}
];
`;
  mkdirSync(dirname(destination), { recursive: true });
  writeFileSync(destination, source, 'utf8');
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));
  const target = resolve(process.cwd(), 'src/core/solutionCounts.generated.ts');

  if (args.merge !== null) {
    const counts = new Array<number>(TABLE_SIZE).fill(0);
    for (const file of args.merge) {
      const part: Record<string, number> = JSON.parse(readFileSync(file, 'utf8')) as Record<
        string,
        number
      >;
      for (const [index, value] of Object.entries(part)) counts[Number(index)] = value;
    }
    writeTable(counts, args.out ?? target);
    const filled = counts.filter((value) => value > 0).length;
    process.stdout.write(`merged ${args.merge.length} parts, ${filled} counted dates\n`);
    return;
  }

  const all = combinations();
  const mine = all.filter((_date, index) => index % args.shards === args.shard);
  const results: Record<number, number> = {};
  const startedAt = Date.now();

  mine.forEach((date, done) => {
    results[tableIndex(date.month, date.day, date.weekday)] = countSolutions(date);
    if ((done + 1) % 25 === 0 || done + 1 === mine.length) {
      const elapsed = (Date.now() - startedAt) / 1000;
      const rate = (done + 1) / elapsed;
      const left = Math.round((mine.length - done - 1) / rate);
      process.stdout.write(
        `shard ${args.shard}: ${done + 1}/${mine.length} · ${elapsed.toFixed(0)}s elapsed · ~${left}s left\n`,
      );
    }
  });

  if (args.shards > 1 || args.out !== null) {
    const destination = args.out ?? `solution-counts-${args.shard}.json`;
    writeFileSync(destination, JSON.stringify(results), 'utf8');
    process.stdout.write(`shard ${args.shard}: wrote ${destination}\n`);
    return;
  }

  const counts = new Array<number>(TABLE_SIZE).fill(0);
  for (const [index, value] of Object.entries(results)) counts[Number(index)] = value;
  writeTable(counts, target);
  process.stdout.write(`wrote ${target}\n`);
}

main();

